### ISSUE TITLE
An error occurring when using the StepLR scheduler on the FOLD3D dataset

### ISSUE THREAD

**Issue by arantir123** [DeepGraphLearning/GearNet#36]
Hi, thank you for your amazing work!
I tried to reproduce the GearNet results on Fold3D dataset, I followed the original .yaml file in which the StepLR scheduler was specified. However, there was an error occurring when using the scheduler as follows, I would like to ask what causes this, thank you!

15:28:38   #train: 12312, #valid: 736, #test: 718
Traceback (most recent call last):
  File "script/downstream.py", line 74, in <module>
    solver, scheduler = util.build_downstream_solver(cfg, dataset)
  File "/GearNet-new/util.py", line 121, in build_downstream_solver
    scheduler = core.Configurable.load_config_dict(cfg.scheduler)
  File "/torchdrug/lib/python3.8/site-packages/torchdrug/core/core.py", line 269, in load_config_dict
    return cls(**new_config)
  File "/torchdrug/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/torchdrug/lib/python3.8/site-packages/torchdrug/core/core.py", line 288, in wrapper
    return init(self, *args, **kwargs)
  File "/torchdrug/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 367, in __init__
    super(StepLR, self).__init__(optimizer, last_epoch, verbose)
  File "/torchdrug/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 367, in __init__
    super(StepLR, self).__init__(optimizer, last_epoch, verbose)
  File "/torchdrug/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 367, in __init__
    super(StepLR, self).__init__(optimizer, last_epoch, verbose)
  [Previous line repeated 991 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by Oxer11** [comment]
Hi, sorry for the inconvience. Actually, this is a bug in TorchDrug when reloading the scheduler. This has been fixed in https://github.com/DeepGraphLearning/torchdrug/commit/4ea99a04e258689f944804df091b209bfebea138. Could you try to install the TorchDrug library from the source code and see whether this can be fixed?

**Comment by arantir123** [comment]
Thank you. Seems that the issue has been solved.
