### ISSUE TITLE
PDB file conversion into torchdrug.data.PackedProtein or TorchDrug.data.Protein

### ISSUE THREAD

**Issue by gtamer2** [DeepGraphLearning/GearNet#55]
Hello,

I am getting errors that are blocking me from running GearNet inference on an input PDB file.

First, I loaded a PDB file into a TorchDrug.data.Protein structure as follows:
`protein_graph = torchdrug.data.Protein.from_pdb(path_to_pdb_file)`

Second, I followed the GearNet graph construction laid out in [TorchProtein tutorial 3: Structure-based Protein Property Prediction
](https://torchprotein.ai/tutorial_3). I encapsulated the graph construction logic such that I can access it like:
`gearnet_protein_graph = graph_construction_model(protein_graph)`

However, when running this together:
```
protein_graph = torchdrug.data.Protein.from_pdb(path_to_pdb_file)
gearnet_protein_graph = graph_construction_model(protein_graph)
```

I get the following error: 
```
  File "<path>/torchdrug/layers/geometry/function.py", line 171, in forward
    is_node_in = graph.atom2residue >= (graph.num_cum_residues - graph.num_residues)[graph.atom2graph] - i
AttributeError: 'Protein' object has no attribute 'num_cum_residues'
```

I studied the source code and found that `num_cum_residues` is a property of `TorchDrug.data.PackedProtein` but not of for `torchdrug.data.Protein`.

So, third, I attempted to convert Protein into PackedProtein, with resulting code:
```
        protein_graph = Protein.from_pdb(path_to_pdb_file)
        num_edges = protein_graph.edge_list.shape[0]
        num_residues = protein_graph.residue_type.shape[0]

        packed_protein_graph = PackedProtein(edge_list=protein_graph.edge_list,
                                             atom_type=protein_graph.atom_type,
                                             bond_type=protein_graph.bond_type,
                                             residue_type=protein_graph.residue_type,
                                             view=protein_graph.view,
                                             num_edges=[num_edges],
                                             num_residues=torch.tensor(
                                                 num_residues),
                                             )

        gearnet_protein_graph = self.graph_construction_model(
            packed_protein_graph)
        print("gearnet protein graph: {}".format(gearnet_protein_graph))
        return gearnet_protein_graph
```

However, now I get an error that `ValueError: Expect node attribute `atom_type` to have shape (16344, *), but found torch.Size([16448])` (16448 is, I assume, the number of nodes derived from the edge_list).

Is this the right approach to run inference with Gearnet? I downloaded the PDB files directly from https://www.wwpdb.org, so I'd like to think the issue is not in the input data. Thank you in advance for any guidance here.

Example PDB files that can't be processed:
- [5XFH.cif.gz](https://github.com/DeepGraphLearning/GearNet/files/13207122/5XFH.cif.gz)
- [6CM2.cif.gz](https://github.com/DeepGraphLearning/GearNet/files/13207135/6CM2.cif.gz)

**Comment by gtamer2** [comment]
I have studied the pretrain/downstream scripts' way of initializing a dataset as here: https://github.com/DeepGraphLearning/GearNet/blob/780809836c87c1028b312241215e856d9b0634b2/script/pretrain.py#L65, but from studying the [Torchdrug source code](https://github.com/DeepGraphLearning/torchdrug/blob/97858c6cf9c41d12d517d911bc2a32d5fb87d075/torchdrug/core/core.py#L256-L278), this method is specific to TorchDrug-registered datasets.

**Comment by mpedraza98** [comment]
I have tried with 
```
_protein = data.Protein.pack([protein])   
protein_ = graph_construction_model(_protein)
```

as described in the tutorials and had no issue at all

**Comment by gtamer2** [comment]
This fixed it for me. Not sure why I missed that option. Thanks!

**Comment by Tizzzzy** [comment]
> This fixed it for me. Not sure why I missed that option. Thanks!

Hi gtamer2,
Can you please help me? I want to load the released pretrained model weight, and then pass a pdb file to the model. In this case, I can get the latent representation of the protein pdb file from the model.
Now I think I can successfully load the released pretrained weight, however, I am stuck at passing the pdb file to the model. Here is how I pass it:
``` python
def extract_representation(model, protein_structure_path):
    protein = Protein.from_pdb(protein_structure_path)
    
    _protein = Protein.pack([protein])

    input_feature = protein.atom2graph
    
    with torch.no_grad():
        representation = model(_protein, input_feature)
    
    # Return the output, which is the protein's representation
    return representation
```
I think GearNet model takes two parameter: 1. a Graph object, 2. input (not sure what this is). However, it seems like either `_protein ` is wrong or `input_feature` is wrong. With this code, I am getting this error:
``` bash
Traceback (most recent call last):
  File "/content/GearNet-main/script/test.py", line 62, in <module>
    main()
  File "/content/GearNet-main/script/test.py", line 58, in main
    representation = extract_representation(model, args.pdb)
  File "/content/GearNet-main/script/test.py", line 43, in extract_representation
    representation = model(_protein, input_feature)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/GearNet-main/gearnet/model.py", line 115, in forward
    edge_hidden = self.edge_layers[i](line_graph, edge_hidden)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/GearNet-main/gearnet/layer.py", line 132, in forward
    update = self.aggregate(graph, message)
  File "/content/GearNet-main/gearnet/layer.py", line 118, in aggregate
    update = update.view(graph.num_node, self.num_relation * self.input_dim)
RuntimeError: shape '[4944, 472]' is invalid for input of size 711936
```
Can you please help me with this. Thank you
